version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    container_name: ${POSTGRES_CONTAINER_NAME:-n8n_postgres}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:${N8N_VERSION:-latest}
    container_name: ${N8N_CONTAINER_NAME:-n8n_app}
    restart: always
    depends_on:
      - postgres
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST:-postgres}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT:-5432}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB_NAME}

      # Security
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE:-true}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: ${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:-true}

      # Server
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      NODE_ENV: ${NODE_ENV:-production}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-Asia/Kolkata}

    volumes:
      - ${N8N_DATA_PATH:-./data/n8n}:/home/node/.n8n
